In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pickle

In [5]:
x = pickle.load(open('./data/fundamentals2.pkl', 'rb'))
y = pickle.load(open('./data/performance2.pkl', 'rb'))

In [6]:
print(x.shape)
print(y.shape)

(27105, 74)
(27105, 8)

In [7]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27105 entries, 0 to 27104
Data columns (total 74 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Ticker                                           27105 non-null  object
 1   Report Date                                      27105 non-null  datetime64[ns]
 2   SimFinId                                         27105 non-null  int64
 3   Currency                                         27105 non-null  object
 4   Fiscal Year                                      27105 non-null  int64
 5   Fiscal Period_x                                  27105 non-null  object
 6   Publish Date                                     27105 non-null  datetime64[ns]
 7   Restated Date_x                                  27105 non-null  datetime64[ns]
 8   Shares (Basic)_x                                 27105 non-null  float64
 9   Shares (Diluted)_x                               27105 non-null  float64
 10  Revenue                                          26449 non-null  float64
 11  Cost of Revenue                                  24458 non-null  float64
 12  Gross Profit                                     24435 non-null  float64
 13  Operating Expenses                               27060 non-null  float64
 14  Selling, General & Administrative                25805 non-null  float64
 15  Research & Development                           11617 non-null  float64
 16  Depreciation & Amortization_x                    11819 non-null  float64
 17  Operating Income (Loss)                          27104 non-null  float64
 18  Non-Operating Income (Loss)                      26954 non-null  float64
 19  Interest Expense, Net                            24104 non-null  float64
 20  Pretax Income (Loss), Adj.                       27105 non-null  int64
 21  Abnormal Gains (Losses)                          15377 non-null  float64
 22  Pretax Income (Loss)                             27105 non-null  int64
 23  Income Tax (Expense) Benefit, Net                24828 non-null  float64
 24  Income (Loss) from Continuing Operations         27105 non-null  int64
 25  Net Extraordinary Gains (Losses)                 3400 non-null   float64
 26  Net Income                                       27105 non-null  int64
 27  Net Income (Common)                              27105 non-null  int64
 28  Fiscal Period_y                                  27105 non-null  object
 29  Restated Date_y                                  27105 non-null  datetime64[ns]
 30  Shares (Basic)_y                                 27105 non-null  float64
 31  Shares (Diluted)_y                               27105 non-null  float64
 32  Cash, Cash Equivalents & Short Term Investments  27087 non-null  float64
 33  Accounts & Notes Receivable                      24730 non-null  float64
 34  Inventories                                      18121 non-null  float64
 35  Total Current Assets                             27105 non-null  float64
 36  Property, Plant & Equipment, Net                 26743 non-null  float64
 37  Long Term Investments & Receivables              7057 non-null   float64
 38  Other Long Term Assets                           26869 non-null  float64
 39  Total Noncurrent Assets                          27060 non-null  float64
 40  Total Assets                                     27105 non-null  int64
 41  Payables & Accruals                              27037 non-null  float64
 42  Short Term Debt                                  17265 non-null  float64
 43  Total Current Liabilities                        27105 non-null  int64
 44  Long Term Debt                                   21629 non-null  float64
 45  Total Noncurrent Liabilities                     26841 non-null  float64
 46  Total Liabilities                                27105 non-null  int64
 47  Share Capital & Additional Paid-In Capital       26733 non-null  float64
 48  Treasury Stock                                   12107 non-null  float64
 49  Retained Earnings                                25969 non-null  float64
 50  Total Equity                                     27103 non-null  float64
 51  Total Liabilities & Equity                       27105 non-null  int64
 52  Fiscal Period                                    27105 non-null  object
 53  Restated Date                                    27105 non-null  datetime64[ns]
 54  Shares (Basic)                                   27105 non-null  float64
 55  Shares (Diluted)                                 27105 non-null  float64
 56  Net Income/Starting Line                         26786 non-null  float64
 57  Depreciation & Amortization_y                    26417 non-null  float64
 58  Non-Cash Items                                   26786 non-null  float64
 59  Change in Working Capital                        26590 non-null  float64
 60  Change in Accounts Receivable                    2164 non-null   float64
 61  Change in Inventories                            1579 non-null   float64
 62  Change in Accounts Payable                       1726 non-null   float64
 63  Change in Other                                  2521 non-null   float64
 64  Net Cash from Operating Activities               27103 non-null  float64
 65  Change in Fixed Assets & Intangibles             26508 non-null  float64
 66  Net Change in Long Term Investment               10034 non-null  float64
 67  Net Cash from Acquisitions & Divestitures        12682 non-null  float64
 68  Net Cash from Investing Activities               26957 non-null  float64
 69  Dividends Paid                                   13017 non-null  float64
 70  Cash from (Repayment of) Debt                    22537 non-null  float64
 71  Cash from (Repurchase of) Equity                 22751 non-null  float64
 72  Net Cash from Financing Activities               26957 non-null  float64
 73  Net Change in Cash                               27105 non-null  int64
dtypes: datetime64[ns](5), float64(52), int64(12), object(5)
memory usage: 15.3+ MB

As there are still some null values, we would need to fix these as any feature engineered ratio could give us an error. Let's fill these null values with zero first.

In [9]:
x = x.fillna(0)

In [12]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27105 entries, 0 to 27104
Data columns (total 74 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Ticker                                           27105 non-null  object
 1   Report Date                                      27105 non-null  datetime64[ns]
 2   SimFinId                                         27105 non-null  int64
 3   Currency                                         27105 non-null  object
 4   Fiscal Year                                      27105 non-null  int64
 5   Fiscal Period_x                                  27105 non-null  object
 6   Publish Date                                     27105 non-null  datetime64[ns]
 7   Restated Date_x                                  27105 non-null  datetime64[ns]
 8   Shares (Basic)_x                                 27105 non-null  float64
 9   Shares (Diluted)_x                               27105 non-null  float64
 10  Revenue                                          27105 non-null  float64
 11  Cost of Revenue                                  27105 non-null  float64
 12  Gross Profit                                     27105 non-null  float64
 13  Operating Expenses                               27105 non-null  float64
 14  Selling, General & Administrative                27105 non-null  float64
 15  Research & Development                           27105 non-null  float64
 16  Depreciation & Amortization_x                    27105 non-null  float64
 17  Operating Income (Loss)                          27105 non-null  float64
 18  Non-Operating Income (Loss)                      27105 non-null  float64
 19  Interest Expense, Net                            27105 non-null  float64
 20  Pretax Income (Loss), Adj.                       27105 non-null  int64
 21  Abnormal Gains (Losses)                          27105 non-null  float64
 22  Pretax Income (Loss)                             27105 non-null  int64
 23  Income Tax (Expense) Benefit, Net                27105 non-null  float64
 24  Income (Loss) from Continuing Operations         27105 non-null  int64
 25  Net Extraordinary Gains (Losses)                 27105 non-null  float64
 26  Net Income                                       27105 non-null  int64
 27  Net Income (Common)                              27105 non-null  int64
 28  Fiscal Period_y                                  27105 non-null  object
 29  Restated Date_y                                  27105 non-null  datetime64[ns]
 30  Shares (Basic)_y                                 27105 non-null  float64
 31  Shares (Diluted)_y                               27105 non-null  float64
 32  Cash, Cash Equivalents & Short Term Investments  27105 non-null  float64
 33  Accounts & Notes Receivable                      27105 non-null  float64
 34  Inventories                                      27105 non-null  float64
 35  Total Current Assets                             27105 non-null  float64
 36  Property, Plant & Equipment, Net                 27105 non-null  float64
 37  Long Term Investments & Receivables              27105 non-null  float64
 38  Other Long Term Assets                           27105 non-null  float64
 39  Total Noncurrent Assets                          27105 non-null  float64
 40  Total Assets                                     27105 non-null  int64
 41  Payables & Accruals                              27105 non-null  float64
 42  Short Term Debt                                  27105 non-null  float64
 43  Total Current Liabilities                        27105 non-null  int64
 44  Long Term Debt                                   27105 non-null  float64
 45  Total Noncurrent Liabilities                     27105 non-null  float64
 46  Total Liabilities                                27105 non-null  int64
 47  Share Capital & Additional Paid-In Capital       27105 non-null  float64
 48  Treasury Stock                                   27105 non-null  float64
 49  Retained Earnings                                27105 non-null  float64
 50  Total Equity                                     27105 non-null  float64
 51  Total Liabilities & Equity                       27105 non-null  int64
 52  Fiscal Period                                    27105 non-null  object
 53  Restated Date                                    27105 non-null  datetime64[ns]
 54  Shares (Basic)                                   27105 non-null  float64
 55  Shares (Diluted)                                 27105 non-null  float64
 56  Net Income/Starting Line                         27105 non-null  float64
 57  Depreciation & Amortization_y                    27105 non-null  float64
 58  Non-Cash Items                                   27105 non-null  float64
 59  Change in Working Capital                        27105 non-null  float64
 60  Change in Accounts Receivable                    27105 non-null  float64
 61  Change in Inventories                            27105 non-null  float64
 62  Change in Accounts Payable                       27105 non-null  float64
 63  Change in Other                                  27105 non-null  float64
 64  Net Cash from Operating Activities               27105 non-null  float64
 65  Change in Fixed Assets & Intangibles             27105 non-null  float64
 66  Net Change in Long Term Investment               27105 non-null  float64
 67  Net Cash from Acquisitions & Divestitures        27105 non-null  float64
 68  Net Cash from Investing Activities               27105 non-null  float64
 69  Dividends Paid                                   27105 non-null  float64
 70  Cash from (Repayment of) Debt                    27105 non-null  float64
 71  Cash from (Repurchase of) Equity                 27105 non-null  float64
 72  Net Cash from Financing Activities               27105 non-null  float64
 73  Net Change in Cash                               27105 non-null  int64
dtypes: datetime64[ns](5), float64(52), int64(12), object(5)
memory usage: 15.3+ MB

In [14]:
# Add in two new columns
# Market Cap = Shares (Diluted)_x  x Open Price
# EV = Market cap + LT debt + ST debt - Cash
# EBIT = Net Income - Interest Expense - Income Tax (Expense) Benefit, Net

x['Market Cap'] = x['Shares (Diluted)_x'] * y['Open1']
x['EV'] = x['Market Cap'] + x['Long Term Debt'] + x['Short Term Debt'] - x['Cash, Cash Equivalents & Short Term Investments']
x['EBIT'] = x['Net Income'] - x['Interest Expense, Net'] - x['Income Tax (Expense) Benefit, Net']

In [15]:
x.head()

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period_x,Publish Date,Restated Date_x,Shares (Basic)_x,Shares (Diluted)_x,...,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,Market Cap,EV,EBIT
0,A,2016-10-31,45846,USD,2016,Q4,2016-12-20,2018-12-20,324000000.0,328000000.0,...,-26000000.0,-78000000.0,-38000000.0,27000000.0,-43000000.0,-56000000.0,90000000,1.421224e+10,1.382724e+10,167000000.0
1,A,2017-01-31,45846,USD,2017,Q1,2017-03-08,2018-03-06,322000000.0,326000000.0,...,-69000000.0,-101000000.0,-42000000.0,89000000.0,-93000000.0,-58000000.0,-48000000,1.566104e+10,1.541204e+10,209000000.0
2,A,2017-04-30,45846,USD,2017,Q2,2017-06-06,2018-05-31,321000000.0,325000000.0,...,0.0,-43000000.0,-43000000.0,52000000.0,-75000000.0,-67000000.0,148000000,1.803750e+10,1.769150e+10,206000000.0
3,A,2017-07-31,45846,USD,2017,Q3,2017-09-06,2018-08-30,321000000.0,326000000.0,...,-57000000.0,-101000000.0,-42000000.0,39000000.0,32000000.0,29000000.0,174000000,1.966432e+10,1.918232e+10,206000000.0
4,A,2017-10-31,45846,USD,2017,Q4,2017-12-21,2018-12-20,324000000.0,327000000.0,...,0.0,-60000000.0,-43000000.0,-70000000.0,8000000.0,-106000000.0,115000000,2.215098e+10,2.148398e+10,239000000.0

In [23]:
# Feature engineer many different financial ratios
# EV/EBIT
x['EV_EBIT'] = x['EV']/x['EBIT']

# Operating Income over (Net working capital + Fixed assets)
x['OI_NWCFA'] = x['Operating Income (Loss)']/\
(x['Total Current Assets'] - x['Total Current Liabilities'] + x['Property, Plant & Equipment, Net'])

# Price to earnings
x['PE'] = x['Market Cap']/x['Net Income']

# Price to book
x['PB'] = x['Market Cap']/x['Total Equity']

# Price to sales
x['PS'] = x['Market Cap']/x['Revenue']

# Operating Income over Interest Expense
x['OI_IntExp'] = x['Operating Income (Loss)']/ -x['Interest Expense, Net']

# Working Capital Ratio (CA/CL)
x['WorkingCap'] = x['Total Current Assets']/ x['Total Current Liabilities']

# Return on Equity
x['ROE'] = x['Net Income']/ x['Total Equity']

# Return on Capital Employed
x['ROCE'] = x['EBIT']/ (x['Total Assets'] - x['Total Current Liabilities'])

# Debt/Equity
x['DE'] = x['Total Liabilities']/ x['Total Equity']

# Debt Ratio
x['DebtRatio'] = x['Total Assets']/ x['Total Liabilities']

# Cash Ratio
x['CashRatio'] = x['Cash, Cash Equivalents & Short Term Investments']/ x['Total Current Liabilities']

# Asset Turnover
x['AssetTurnover'] = x['Revenue']/ x['Property, Plant & Equipment, Net']

# Gross Profit Margin
x['GPM'] = x['Gross Profit']/ x['Revenue']

# Working Capital over total assets
x['WC_TA'] = (x['Total Current Assets'] - x['Total Current Liabilities'])/ x['Total Assets']

# Retained earnings over total assets
x['RE_TA'] = x['Retained Earnings']/ x['Total Assets']

# EBIT over total assets
x['EBIT_TA'] = x['EBIT']/ x['Total Assets']

# Equity over liabilities
x['Equity_Liab'] = x['Total Equity']/ x['Total Liabilities']

In [24]:
x.head()

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period_x,Publish Date,Restated Date_x,Shares (Basic)_x,Shares (Diluted)_x,...,ROCE,DE,DebtRatio,CashRatio,AssetTurnover,GPM,WC_TA,RE_TA,EBIT_TA,Equity_Liab
0,A,2016-10-31,45846,USD,2016,Q4,2016-12-20,2018-12-20,324000000.0,328000000.0,...,0.024383,0.835610,2.196731,2.422222,1.738654,0.529253,0.345137,0.781242,0.021427,1.196731
1,A,2017-01-31,45846,USD,2017,Q1,2017-03-08,2018-03-06,322000000.0,326000000.0,...,0.030812,0.830698,2.203807,2.057851,1.633997,0.537957,0.323425,-0.057546,0.026550,1.203807
2,A,2017-04-30,45846,USD,2017,Q2,2017-06-06,2018-05-31,321000000.0,325000000.0,...,0.030165,0.832229,2.201593,2.012637,1.632593,0.537205,0.325973,-0.049027,0.025699,1.201593
3,A,2017-07-31,45846,USD,2017,Q3,2017-09-06,2018-08-30,321000000.0,326000000.0,...,0.029345,0.791585,2.263288,2.065270,1.555866,0.535009,0.333495,-0.031473,0.024936,1.263288
4,A,2017-10-31,45846,USD,2017,Q4,2017-12-21,2018-12-20,324000000.0,327000000.0,...,0.033366,0.742709,2.346422,2.120348,1.570674,0.544155,0.344885,-0.014954,0.028365,1.346422