In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
import simfin as sf

# Set your SimFin+ API-key for downloading data.
sf.set_api_key('nYdjeL237mt7QaQ4OZTaPa4Xn3YECrTH')

# Set the local directory where data-files are stored.
# The directory will be created if it does not already exist.
sf.set_data_dir('~/simfin_data/')

# Download the data from the SimFin server and load into a Pandas DataFrame.
df = sf.load_income(variant='quarterly', market='us')
df1 = sf.load_balance(variant='quarterly', market='us')
df2 = sf.load_cashflow(variant='quarterly', market='us')

# Print the first rows of the data.
df.head()

Dataset "us-income-quarterly" on disk (4 days old).
- Loading from disk ... Done!
Dataset "us-balance-quarterly" on disk (4 days old).
- Loading from disk ... Done!
Dataset "us-cashflow-quarterly" on disk (4 days old).
- Loading from disk ... Done!

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2016-10-31      45846      USD         2016            Q4   2016-12-20
       2017-01-31      45846      USD         2017            Q1   2017-03-08
       2017-04-30      45846      USD         2017            Q2   2017-06-06
       2017-07-31      45846      USD         2017            Q3   2017-09-06
       2017-10-31      45846      USD         2017            Q4   2017-12-21

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2016-10-31     2018-12-20     324000000.0       328000000.0
       2017-01-31     2018-03-06     322000000.0       326000000.0
       2017-04-30     2018-05-31     321000000.0       325000000.0
       2017-07-31     2018-08-30     321000000.0       326000000.0
       2017-10-31     2018-12-20     324000000.0       327000000.0

                         Revenue  Cost of Revenue  ...  \
Ticker Report Date                                 ...
A      2016-10-31   1.111000e+09     -523000000.0  ...
       2017-01-31   1.067000e+09     -493000000.0  ...
       2017-04-30   1.102000e+09     -510000000.0  ...
       2017-07-31   1.114000e+09     -518000000.0  ...
       2017-10-31   1.189000e+09     -542000000.0  ...

                    Non-Operating Income (Loss)  Interest Expense, Net  \
Ticker Report Date
A      2016-10-31                   -32000000.0            -16000000.0
       2017-01-31                   -13000000.0            -16000000.0
       2017-04-30                   -10000000.0            -15000000.0
       2017-07-31                    -8000000.0            -13000000.0
       2017-10-31                    -7000000.0            -13000000.0

                    Pretax Income (Loss), Adj.  Abnormal Gains (Losses)  \
Ticker Report Date
A      2016-10-31                    151000000                      NaN
       2017-01-31                    193000000                      NaN
       2017-04-30                    191000000                      NaN
       2017-07-31                    193000000                      NaN
       2017-10-31                    226000000                      NaN

                    Pretax Income (Loss)  Income Tax (Expense) Benefit, Net  \
Ticker Report Date
A      2016-10-31              151000000                        -25000000.0
       2017-01-31              193000000                        -25000000.0
       2017-04-30              191000000                        -27000000.0
       2017-07-31              193000000                        -18000000.0
       2017-10-31              226000000                        -49000000.0

                    Income (Loss) from Continuing Operations  \
Ticker Report Date
A      2016-10-31                                  126000000
       2017-01-31                                  168000000
       2017-04-30                                  164000000
       2017-07-31                                  175000000
       2017-10-31                                  177000000

                    Net Extraordinary Gains (Losses)  Net Income  \
Ticker Report Date
A      2016-10-31                                NaN   126000000
       2017-01-31                                NaN   168000000
       2017-04-30                                NaN   164000000
       2017-07-31                                NaN   175000000
       2017-10-31                                NaN   177000000

                    Net Income (Common)
Ticker Report Date
A      2016-10-31             126000000
       2017-01-31             168000000
       2017-04-30             164000000
       2017-07-31             175000000
       2017-10-31             177000000

[5 rows x 26 columns]

In [3]:
df1.head()

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2016-10-31      45846      USD         2016            Q4   2016-12-20
       2017-01-31      45846      USD         2017            Q1   2017-03-08
       2017-04-30      45846      USD         2017            Q2   2017-06-06
       2017-07-31      45846      USD         2017            Q3   2017-09-06
       2017-10-31      45846      USD         2017            Q4   2017-12-21

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2016-10-31     2017-12-21     324000000.0       328000000.0
       2017-01-31     2017-03-08     322000000.0       326000000.0
       2017-04-30     2017-06-06     321000000.0       325000000.0
       2017-07-31     2017-09-06     321000000.0       326000000.0
       2017-10-31     2018-12-20     324000000.0       327000000.0

                    Cash, Cash Equivalents & Short Term Investments  \
Ticker Report Date
A      2016-10-31                                      2.289000e+09
       2017-01-31                                      2.241000e+09
       2017-04-30                                      2.389000e+09
       2017-07-31                                      2.563000e+09
       2017-10-31                                      2.678000e+09

                    Accounts & Notes Receivable  ...  Short Term Debt  \
Ticker Report Date                               ...
A      2016-10-31                   631000000.0  ...              0.0
       2017-01-31                   653000000.0  ...      190000000.0
       2017-04-30                   677000000.0  ...      241000000.0
       2017-07-31                   678000000.0  ...      280000000.0
       2017-10-31                   724000000.0  ...      210000000.0

                    Total Current Liabilities  Long Term Debt  \
Ticker Report Date
A      2016-10-31                   945000000    1.904000e+09
       2017-01-31                  1089000000    1.802000e+09
       2017-04-30                  1187000000    1.802000e+09
       2017-07-31                  1241000000    1.801000e+09
       2017-10-31                  1263000000    1.801000e+09

                    Total Noncurrent Liabilities  Total Liabilities  \
Ticker Report Date
A      2016-10-31                   2.603000e+09         3548000000
       2017-01-31                   2.483000e+09         3572000000
       2017-04-30                   2.454000e+09         3641000000
       2017-07-31                   2.409000e+09         3650000000
       2017-10-31                   2.328000e+09         3591000000

                    Share Capital & Additional Paid-In Capital  \
Ticker Report Date
A      2016-10-31                                 9.165000e+09
       2017-01-31                                 5.239000e+09
       2017-04-30                                 5.242000e+09
       2017-07-31                                 5.285000e+09
       2017-10-31                                 5.303000e+09

                    Treasury Stock  Retained Earnings  Total Equity  \
Ticker Report Date
A      2016-10-31    -1.050800e+10       6.089000e+09  4.246000e+09
       2017-01-31     0.000000e+00      -4.530000e+08  4.300000e+09
       2017-04-30     0.000000e+00      -3.930000e+08  4.375000e+09
       2017-07-31     0.000000e+00      -2.600000e+08  4.611000e+09
       2017-10-31              NaN      -1.260000e+08  4.835000e+09

                    Total Liabilities & Equity
Ticker Report Date
A      2016-10-31                   7794000000
       2017-01-31                   7872000000
       2017-04-30                   8016000000
       2017-07-31                   8261000000
       2017-10-31                   8426000000

[5 rows x 28 columns]

In [4]:
df2.tail()

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
ZYXI   2020-06-30     171401      USD         2020            Q2   2020-07-28
       2020-09-30     171401      USD         2020            Q3   2020-10-27
       2020-12-31     171401      USD         2020            Q4   2021-02-25
       2021-03-31     171401      USD         2021            Q1   2021-04-29
       2021-06-30     171401      USD         2021            Q2   2021-07-29

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
ZYXI   2020-06-30     2021-04-29      36611300.0        37899400.0
       2020-09-30     2021-07-29      37945600.0        39035700.0
       2020-12-31     2021-11-02      38262400.0        39189700.0
       2021-03-31     2022-04-28      38320700.0        38320700.0
       2021-06-30     2022-04-28      38320700.0        38320700.0

                    Net Income/Starting Line  Depreciation & Amortization  \
Ticker Report Date
ZYXI   2020-06-30                  3017000.0                     285000.0
       2020-09-30                  1333000.0                     505000.0
       2020-12-31                  1787000.0                     530000.0
       2021-03-31                  -706000.0                     487000.0
       2021-06-30                  2808000.0                     607000.0

                    ...  Net Cash from Operating Activities  \
Ticker Report Date  ...
ZYXI   2020-06-30   ...                           2651000.0
       2020-09-30   ...                           -769000.0
       2020-12-31   ...                          -1696000.0
       2021-03-31   ...                          -5305000.0
       2021-06-30   ...                           1027000.0

                    Change in Fixed Assets & Intangibles  \
Ticker Report Date
ZYXI   2020-06-30                              -357000.0
       2020-09-30                              -105000.0
       2020-12-31                              -226000.0
       2021-03-31                              -299000.0
       2021-06-30                               -55000.0

                    Net Change in Long Term Investment  \
Ticker Report Date
ZYXI   2020-06-30                                  NaN
       2020-09-30                                  NaN
       2020-12-31                                  NaN
       2021-03-31                                  NaN
       2021-06-30                                  NaN

                    Net Cash from Acquisitions & Divestitures  \
Ticker Report Date
ZYXI   2020-06-30                                         NaN
       2020-09-30                                         NaN
       2020-12-31                                         NaN
       2021-03-31                                         NaN
       2021-06-30                                         NaN

                    Net Cash from Investing Activities  Dividends Paid  \
Ticker Report Date
ZYXI   2020-06-30                            -357000.0             NaN
       2020-09-30                            -105000.0             NaN
       2020-12-31                            -226000.0             NaN
       2021-03-31                            -299000.0             NaN
       2021-06-30                             -55000.0             NaN

                    Cash from (Repayment of) Debt  \
Ticker Report Date
ZYXI   2020-06-30                        -16000.0
       2020-09-30                        -15000.0
       2020-12-31                        -15000.0
       2021-03-31                        -23000.0
       2021-06-30                        -21000.0

                    Cash from (Repurchase of) Equity  \
Ticker Report Date
ZYXI   2020-06-30                            53000.0
       2020-09-30                         25202000.0
       2020-12-31                           293000.0
       2021-03-31                           -48000.0
       2021-06-30                         -1984000.0

                    Net Cash from Financing Activities  Net Change in Cash
Ticker Report Date
ZYXI   2020-06-30                              37000.0             2331000
       2020-09-30                           25187000.0            24313000
       2020-12-31                            -134000.0            -2056000
       2021-03-31                            -130000.0            -5734000
       2021-06-30                           -2081000.0            -1109000

[5 rows x 26 columns]

In [5]:
print('Income Statement CSV data is: ',
df.shape)
print('Balance Sheet CSV data is: ',
df1.shape)
print('Cash Flow CSV data is: ' ,
df2.shape)

Income Statement CSV data is:  (36685, 26)
Balance Sheet CSV data is:  (36685, 28)
Cash Flow CSV data is:  (36685, 26)

In [6]:
# Merge the data together
result = pd.merge(df, df1,\
on=['Ticker','SimFinId','Currency',\
'Fiscal Year','Report Date','Publish Date'], how='inner')

result = pd.merge(result, df2,\
on=['Ticker','SimFinId','Currency',\
'Fiscal Year','Report Date','Publish Date'], how='inner')

result.reset_index(inplace=True)

# dates in correct format
result["Report Date"] = pd.to_datetime(result["Report Date"])
result["Publish Date"] = pd.to_datetime(result["Publish Date"])
print('Merged X data matrix shape is: ', result.shape)

Merged X data matrix shape is:  (36685, 74)

In [7]:
result.head()

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period_x,Publish Date,Restated Date_x,Shares (Basic)_x,Shares (Diluted)_x,...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,2016-10-31,45846,USD,2016,Q4,2016-12-20,2018-12-20,324000000.0,328000000.0,...,234000000.0,-52000000.0,0.0,-26000000.0,-78000000.0,-38000000.0,27000000.0,-43000000.0,-56000000.0,90000000
1,A,2017-01-31,45846,USD,2017,Q1,2017-03-08,2018-03-06,322000000.0,326000000.0,...,116000000.0,-32000000.0,NaN,-69000000.0,-101000000.0,-42000000.0,89000000.0,-93000000.0,-58000000.0,-48000000
2,A,2017-04-30,45846,USD,2017,Q2,2017-06-06,2018-05-31,321000000.0,325000000.0,...,257000000.0,-43000000.0,NaN,0.0,-43000000.0,-43000000.0,52000000.0,-75000000.0,-67000000.0,148000000
3,A,2017-07-31,45846,USD,2017,Q3,2017-09-06,2018-08-30,321000000.0,326000000.0,...,228000000.0,-43000000.0,NaN,-57000000.0,-101000000.0,-42000000.0,39000000.0,32000000.0,29000000.0,174000000
4,A,2017-10-31,45846,USD,2017,Q4,2017-12-21,2018-12-20,324000000.0,327000000.0,...,288000000.0,-58000000.0,0.0,0.0,-60000000.0,-43000000.0,-70000000.0,8000000.0,-106000000.0,115000000

In [8]:
df3 = sf.load_shareprices(variant='daily', market='us')

Dataset "us-shareprices-daily" on disk (4 days old).
- Loading from disk ... Done!

In [9]:
df3.reset_index(inplace=True)

In [10]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3157862 entries, 0 to 3157861
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Ticker              object
 1   Date                datetime64[ns]
 2   SimFinId            int64
 3   Open                float64
 4   Low                 float64
 5   High                float64
 6   Close               float64
 7   Adj. Close          float64
 8   Dividend            float64
 9   Volume              int64
 10  Shares Outstanding  float64
dtypes: datetime64[ns](1), float64(7), int64(2), object(1)
memory usage: 265.0+ MB

In [11]:
# function to get price data near date
# return price and volume only

def getPrice (ticker, date, modifier, dailySharePrices):
    windowDays = 5
    rows = dailySharePrices[
    (dailySharePrices["Date"].between(pd.to_datetime(date)
    + pd.Timedelta(days=modifier),
    pd.to_datetime(date)
    + pd.Timedelta(days=windowDays
    +modifier)
    )
    ) & (dailySharePrices["Ticker"]==ticker)]
    
    if rows.empty:
        return [ticker, np.float("NaN"),\
        np.datetime64('NaT'),\
        np.float("NaN")]
    else:
        return [ticker, rows.iloc[0]["Open"],\
        rows.iloc[0]["Date"],\
        rows.iloc[0]["Volume"]*rows.iloc[0]["Open"]]

In [12]:
getPrice('A', '2016-10-31', 2, df3)

['A', 43.47, Timestamp('2016-11-02 00:00:00'), 97391405.16]

In [14]:
def getYPricesReportDateAndTargetDate(x, d, modifier=365):
    ''' Takes in all fundamental data X, all stock prices over time y,
    and modifier (days), and returns the stock price info for the
    data report date, as well as the stock price one year from that date
    (if modifier is left as modifier=365)
    '''
    # Preallocation list of list of 2
    # [(price at date) (price at date + modifier)]
    y = [[None]*8 for i in range(len(x))]
    whichDateCol='Publish Date'# or 'Report Date',
    # is the performance date from->to. Want this to be publish date.
    # Because of time lag between report date
    # (which can't be actioned on) and publish date
    # (data we can trade with)
    i=0
    for index in range(len(x)):
        y[i]=(getYPriceDataNearDate(x['Ticker'].iloc[index],
        x[whichDateCol].iloc[index],0,d)
        +getYPriceDataNearDate(x['Ticker'].iloc[index],
        x[whichDateCol].iloc[index],
        modifier, d))
        i=i+1
    return y